import Link from "next/link";
import { ArrowUpRight, CalendarDays, FileWarning, Users } from "lucide-react";

const alerts = [
  { type: "Alerta normativa", title: "Revisión de alturas permitidas", body: "La iniciativa requiere contrastar perfil vial, densidad y estacionamiento con los artículos vinculados del CPU.", priority: "Alta", href: "/proyectos/codigo-alturas", action: "Revisar normativa", icon: FileWarning, tone: "border-l-amber-400" },
  { type: "Audiencia", title: "Densificación, movilidad y espacio público", body: "Audiencia mixta programada con expediente y documentación técnica ya vinculados.", priority: "Próxima", href: "/audiencias", action: "Preparar audiencia", icon: CalendarDays, tone: "border-l-[#1f89f6]" },
  { type: "Participación", title: "Ciclovía en Av. Aconquija", body: "La propuesta concentra aportes ciudadanos y necesita consolidar la consulta institucional previa.", priority: "Media", href: "/proyectos/ciclovia-aconquija", action: "Ver contexto", icon: Users, tone: "border-l-emerald-400" }
];

export function PriorityAlerts() {
  return <section><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Actividad prioritaria</p><h2 className="mt-2 text-xl font-black text-slate-950 dark:text-white">Requiere atención</h2></div><span className="text-xs font-bold text-slate-400">{alerts.length} acciones abiertas</span></div><div className="grid gap-3 xl:grid-cols-3">{alerts.map((item) => { const Icon = item.icon; return <article key={item.title} className={`surface-panel group border-l-[3px] p-5 transition duration-200 hover:-translate-y-0.5 hover:shadow-lg ${item.tone}`}><div className="flex items-start justify-between gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-600 dark:bg-white/[0.06] dark:text-slate-300"><Icon className="h-4 w-4" /></span><span className="rounded-full border border-slate-200 px-2 py-1 text-[10px] font-black uppercase tracking-wider text-slate-500 dark:border-white/10">{item.priority}</span></div><p className="mt-5 text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">{item.type}</p><h3 className="mt-2 font-black text-slate-950 dark:text-white">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{item.body}</p><Link href={item.href} className="mt-4 inline-flex items-center gap-2 text-sm font-black text-[#087bec]">{item.action}<ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link></article>; })}</div></section>;
}
