import Link from "next/link";
import { ArrowUpRight, CheckCircle2, CircleAlert, GitBranch, Scale } from "lucide-react";
import { AppShell } from "@/components/shell";
import { urbanScenarios } from "@/lib/demo/urban-scenarios";

export default function ScenariosPage() {
  return <AppShell>
    <div className="mb-7"><p className="eyebrow">Evidencia para decidir</p><h1 className="mt-2 text-3xl font-black tracking-[-0.035em] text-slate-950 dark:text-white md:text-4xl">Escenarios de decisión</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-500 dark:text-slate-400">Comparación asistida de alternativas urbanas basada en normativa, evidencia técnica y participación.</p></div>
    <div className="grid gap-4 xl:grid-cols-2">{urbanScenarios.map((scenario) => <article key={scenario.id} className="surface-panel group p-5 transition duration-200 hover:-translate-y-0.5 md:p-6"><div className="flex items-start justify-between gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-[#087bec] dark:bg-sky-400/10"><GitBranch className="h-5 w-5" /></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wider ${scenario.missingInformation.length ? "bg-amber-50 text-amber-700 dark:bg-amber-400/10 dark:text-amber-200" : "bg-emerald-50 text-emerald-700"}`}>{scenario.missingInformation.length ? "Requiere información" : "Listo para revisión"}</span></div><h2 className="mt-5 text-xl font-black leading-tight text-slate-950 dark:text-white">{scenario.title.replace("Escenario: ", "")}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-500 dark:text-slate-400">{scenario.executiveSummary}</p><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{scenario.criteria.map((criterion) => <div key={criterion.label} className="rounded-xl bg-slate-50 p-3 dark:bg-white/[0.035]"><span className="text-[9px] font-black uppercase tracking-wider text-slate-400">{criterion.label}</span><strong className="mt-1 block text-xs text-slate-700 dark:text-slate-200">{criterion.value}</strong></div>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 dark:border-white/10"><div className="flex items-center gap-2 text-xs text-slate-400">{scenario.missingInformation.length ? <CircleAlert className="h-4 w-4 text-amber-500" /> : <CheckCircle2 className="h-4 w-4 text-emerald-500" />}{scenario.missingInformation.length} puntos de información faltante</div><Link href={`/escenarios/${scenario.id}`} className="inline-flex items-center gap-1 text-sm font-black text-[#087bec]">Evaluar<ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link></div></article>)}</div>
    <section className="surface-panel mt-5 p-5 md:p-6"><div className="flex items-center gap-2"><Scale className="h-5 w-5 text-[#1f89f6]" /><h2 className="font-black text-slate-950 dark:text-white">Criterio institucional</h2></div><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Los indicadores expresan categorías presentes en las fichas actuales. Cuando falte evidencia, UrbanIA lo señala explícitamente y no calcula porcentajes sin respaldo.</p></section>
  </AppShell>;
}
