"use client";

import { AnimatePresence, motion } from "framer-motion";
import { useMemo, useState } from "react";
import { BookOpen, Check, ChevronRight, Clipboard, FileWarning, Link2, Plus, Search, X } from "lucide-react";
import type { NormativeExplorerArticle, NormativeExplorerData, NormativeExplorerLink } from "@/lib/normative/data";
import { normalizeForSearch } from "@/lib/normative/parser";

const relationshipLabels: Record<string, string> = { APPLIES: "Aplica", REFERENCES: "Referencia", SUPPORTS: "Sustenta", REQUIRES_REVIEW: "Requiere revisión", POTENTIAL_CONFLICT: "Posible conflicto", MODIFIES: "Modifica" };

export function NormativeExplorer({ data }: { data: NormativeExplorerData }) {
  const [selectedId, setSelectedId] = useState(data.articles[0]?.id ?? "");
  const [query, setQuery] = useState("");
  const [chapterId, setChapterId] = useState<string>("all");
  const [relationsOpen, setRelationsOpen] = useState(false);
  const [localLinks, setLocalLinks] = useState<Record<string, NormativeExplorerLink[]>>({});
  const selected = data.articles.find((article) => article.id === selectedId) ?? data.articles[0];
  const normalizedQuery = normalizeForSearch(query);
  const filtered = useMemo(() => data.articles.filter((article) => (chapterId === "all" || article.chapterId === chapterId) && (!normalizedQuery || article.normalizedContent.includes(normalizedQuery) || article.number === normalizedQuery)), [chapterId, data.articles, normalizedQuery]);
  const definitions = filtered.filter((article) => Number(article.number) >= 4 && Number(article.number) <= 9);
  const regularResults = filtered.filter((article) => !definitions.includes(article));
  const selectedChapter = data.chapters.find((chapter) => chapter.id === selected?.chapterId);
  const links = selected ? [...selected.links, ...(localLinks[selected.id] ?? [])] : [];

  function selectArticle(article: NormativeExplorerArticle) {
    setSelectedId(article.id);
    setRelationsOpen(false);
    window.history.replaceState(null, "", `#articulo-${article.number}`);
  }

  return <div>
    <header className="mb-6">
      <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">Infraestructura normativa</p><h1 className="mt-2 text-3xl font-black tracking-[-0.035em] text-slate-950 dark:text-white md:text-4xl">Código de Planeamiento Urbano</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-500 dark:text-slate-400">Explorá la normativa urbana, sus artículos, conceptos y relaciones territoriales.</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800 dark:border-amber-400/20 dark:bg-amber-400/10 dark:text-amber-100"><strong className="block">Fuente normativa · texto ordenado a mayo de 2014</strong><span className="mt-1 block opacity-80">Ordenanza N.º {data.document.ordinanceNumber} · vigencia posterior no verificada</span></div></div>
      <div className="mt-5 grid gap-3 md:grid-cols-[minmax(0,1fr)_260px]"><label className="surface-panel flex items-center gap-3 px-4 py-3"><Search className="h-5 w-5 text-[#1f89f6]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar altura máxima, estacionamiento, FOT, distrito..." className="min-w-0 flex-1 bg-transparent text-sm outline-none" />{query && <button onClick={() => setQuery("")} className="text-slate-400"><X className="h-4 w-4" /></button>}</label><div className="surface-panel flex items-center justify-between px-4 py-3 text-xs"><span className="text-slate-400">Fuente</span><strong className="text-slate-700 dark:text-slate-200">{data.source === "database" ? "Base estructurada" : "Archivo verificado"}</strong></div></div>
    </header>

    <div className="grid gap-4 xl:grid-cols-[250px_minmax(0,1fr)_300px]">
      <aside className="surface-panel h-fit overflow-hidden xl:sticky xl:top-24"><div className="border-b border-slate-200 p-4 dark:border-white/10"><p className="text-xs font-black uppercase tracking-[0.14em] text-slate-400">Índice del Código</p><p className="mt-1 text-xs text-slate-400">{data.chapters.length} capítulos · {data.articles.length} artículos</p></div><div className="urban-scrollbar max-h-[65vh] overflow-y-auto p-2"><ChapterButton active={chapterId === "all"} label="Todos los artículos" count={data.articles.length} onClick={() => setChapterId("all")} />{data.chapters.map((chapter) => <ChapterButton key={chapter.id} active={chapterId === chapter.id} label={`Capítulo ${chapter.number}`} detail={chapter.title} count={data.articles.filter((article) => article.chapterId === chapter.id).length} onClick={() => setChapterId(chapter.id)} />)}</div></aside>

      <main className="min-w-0">
        {query || chapterId !== "all" ? <SearchResults query={query} definitions={definitions} articles={regularResults} onSelect={selectArticle} /> : null}
        {selected ? <AnimatePresence mode="wait"><motion.article key={selected.id} id={`articulo-${selected.number}`} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="surface-panel overflow-hidden"><div className="border-b border-slate-200 bg-slate-50/70 p-5 dark:border-white/10 dark:bg-white/[0.02] md:p-7"><p className="text-xs font-bold text-slate-400">Capítulo {selectedChapter?.number} · {selectedChapter?.title}</p><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Artículo {selected.number}</p><h2 className="mt-2 max-w-3xl text-2xl font-black leading-tight text-slate-950 dark:text-white md:text-3xl">{selected.title}</h2></div><button onClick={() => navigator.clipboard.writeText(`Código de Planeamiento Urbano, Ordenanza 2648/98, texto ordenado a mayo de 2014, Artículo ${selected.number}`)} className="icon-button" title="Copiar referencia"><Clipboard className="h-4 w-4" /></button></div></div><div className="p-5 md:p-8"><div className="whitespace-pre-line text-[15px] leading-8 text-slate-700 dark:text-slate-300">{selected.content}</div></div><footer className="border-t border-amber-200 bg-amber-50/70 px-5 py-4 text-xs leading-5 text-amber-800 dark:border-amber-400/15 dark:bg-amber-400/[0.06] dark:text-amber-100">El contenido se reproduce desde la fuente original. El análisis debe validarse contra modificaciones normativas posteriores.</footer></motion.article></AnimatePresence> : <EmptyResults />}
      </main>

      <aside className="space-y-4 xl:sticky xl:top-24 xl:self-start">
        <section className="surface-panel p-5"><p className="eyebrow">Contexto relacionado</p><ContextGroup label="Distritos" values={selected?.districts ?? []} empty="Sin distrito explícito detectado" /><ContextGroup label="Artículos relacionados" values={(selected?.references ?? []).map((item) => `Artículo ${item}`)} empty="Sin referencias explícitas" onValueClick={(value) => { const article = data.articles.find((item) => item.number === value.replace("Artículo ", "")); if (article) selectArticle(article); }} /><div className="mt-5 border-t border-slate-200 pt-4 dark:border-white/10"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Relaciones manuales</p><button onClick={() => setRelationsOpen((value) => !value)} className="text-[#087bec]"><Plus className="h-4 w-4" /></button></div>{links.length ? <div className="mt-3 space-y-2">{links.map((link) => <div key={link.id} className="rounded-lg bg-slate-50 p-3 text-xs dark:bg-white/[0.04]"><strong className="text-slate-700 dark:text-slate-200">{link.sourceType}: {link.sourceId}</strong><span className="mt-1 block text-slate-400">{relationshipLabels[link.relationshipType] ?? link.relationshipType}</span></div>)}</div> : <p className="mt-2 text-xs leading-5 text-slate-400">Todavía no hay proyectos, propuestas o audiencias vinculados manualmente.</p>}</div></section>
        {relationsOpen && selected ? <ManualRelationForm article={selected} onCreated={(link) => setLocalLinks((current) => ({ ...current, [selected.id]: [...(current[selected.id] ?? []), link] }))} /> : null}
        <section className="surface-panel p-5"><div className="flex gap-3"><FileWarning className="h-5 w-5 shrink-0 text-amber-500" /><div><h3 className="text-sm font-black text-slate-950 dark:text-white">Referencia histórica controlada</h3><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">Esta versión corresponde al texto ordenado a mayo de 2014. UrbanIA no la presenta automáticamente como normativa vigente actual.</p></div></div></section>
      </aside>
    </div>
  </div>;
}

function SearchResults({ query, definitions, articles, onSelect }: { query: string; definitions: NormativeExplorerArticle[]; articles: NormativeExplorerArticle[]; onSelect: (article: NormativeExplorerArticle) => void }) { const total = definitions.length + articles.length; return <section className="surface-panel mb-4 p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-black text-slate-950 dark:text-white">{query ? `Resultados para “${query}”` : "Artículos del capítulo"}</h2><span className="text-xs text-slate-400">{total} resultados</span></div>{definitions.length ? <ResultGroup title="Definiciones" articles={definitions} onSelect={onSelect} /> : null}{articles.length ? <ResultGroup title="Artículos" articles={articles.slice(0, 20)} onSelect={onSelect} /> : null}{!total ? <p className="py-8 text-center text-sm text-slate-400">No se encontraron coincidencias en la fuente estructurada.</p> : null}</section>; }
function ResultGroup({ title, articles, onSelect }: { title: string; articles: NormativeExplorerArticle[]; onSelect: (article: NormativeExplorerArticle) => void }) { return <div className="mt-4"><p className="mb-2 text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">{title}</p><div className="grid gap-2">{articles.map((article) => <button key={article.id} onClick={() => onSelect(article)} className="group flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-left transition hover:border-sky-300 dark:border-white/10"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-sky-50 text-xs font-black text-sky-700 dark:bg-sky-400/10 dark:text-sky-200">{article.number}</span><span className="min-w-0"><strong className="block truncate text-sm text-slate-700 dark:text-slate-200">{article.title}</strong><span className="mt-1 block truncate text-xs text-slate-400">{article.content.slice(0, 120)}</span></span><ChevronRight className="ml-auto h-4 w-4 shrink-0 text-slate-300 group-hover:text-[#1f89f6]" /></button>)}</div></div>; }
function ChapterButton({ active, label, detail, count, onClick }: { active: boolean; label: string; detail?: string; count: number; onClick: () => void }) { return <button onClick={onClick} className={`mb-1 w-full rounded-xl p-3 text-left transition ${active ? "bg-sky-50 text-sky-800 dark:bg-sky-400/10 dark:text-sky-100" : "text-slate-500 hover:bg-slate-50 dark:hover:bg-white/[0.04]"}`}><span className="flex items-center justify-between gap-2 text-xs font-black"><span>{label}</span><span className="text-[10px] opacity-60">{count}</span></span>{detail && <span className="mt-1 block text-[10px] leading-4 opacity-70">{detail}</span>}</button>; }
function ContextGroup({ label, values, empty, onValueClick }: { label: string; values: string[]; empty: string; onValueClick?: (value: string) => void }) { return <div className="mt-5"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">{label}</p>{values.length ? <div className="mt-2 flex flex-wrap gap-2">{values.map((value) => <button key={value} onClick={() => onValueClick?.(value)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-bold text-slate-600 dark:border-white/10 dark:text-slate-300">{value}</button>)}</div> : <p className="mt-2 text-xs text-slate-400">{empty}</p>}</div>; }
function EmptyResults() { return <div className="surface-panel grid min-h-72 place-items-center p-8 text-center"><div><BookOpen className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 text-sm text-slate-400">Seleccioná un artículo del índice.</p></div></div>; }

function ManualRelationForm({ article, onCreated }: { article: NormativeExplorerArticle; onCreated: (link: NormativeExplorerLink) => void }) {
  const [sourceType, setSourceType] = useState("project"); const [sourceId, setSourceId] = useState(""); const [relationshipType, setRelationshipType] = useState("REFERENCES"); const [status, setStatus] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setStatus(""); try { const response = await fetch("/api/normativa/links", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ articleId: article.id, sourceType, sourceId, relationshipType }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || payload.error); onCreated(payload); setSourceId(""); setStatus("Relación guardada"); } catch (error) { setStatus(error instanceof Error ? error.message : "No se pudo guardar"); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="surface-panel p-5"><div className="flex items-center gap-2"><Link2 className="h-4 w-4 text-[#1f89f6]" /><h3 className="text-sm font-black text-slate-950 dark:text-white">Vincular manualmente</h3></div><div className="mt-4 grid gap-3"><select value={sourceType} onChange={(event) => setSourceType(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-white/10 dark:bg-white/[0.04]"><option value="project">Proyecto</option><option value="proposal">Propuesta</option><option value="hearing">Audiencia</option><option value="document">Documento</option><option value="territory">Territorio</option></select><input required value={sourceId} onChange={(event) => setSourceId(event.target.value)} placeholder="Identificador o expediente" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-white/10 dark:bg-white/[0.04]" /><select value={relationshipType} onChange={(event) => setRelationshipType(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-white/10 dark:bg-white/[0.04]">{Object.entries(relationshipLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button disabled={saving} className="primary-button flex">{saving ? "Guardando..." : <><Check className="h-4 w-4" />Guardar relación</>}</button>{status && <p className="text-xs leading-5 text-slate-500">{status}</p>}</div></form>;
}
