"use client";

import { AnimatePresence, motion } from "framer-motion";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, BarChart3, CalendarDays, Check, Circle, Clock3, FileText, MapPin, Scale, Sparkles, Users } from "lucide-react";
import type { UrbanProject } from "@/lib/demo/urban-projects";

const tabs = ["Resumen", "Mapa", "Normativa", "Audiencias", "Participación", "Documentos", "Análisis IA", "Escenarios", "Historial"] as const;
type Tab = (typeof tabs)[number];

export function Project360({ project }: { project: UrbanProject }) {
  const [tab, setTab] = useState<Tab>("Resumen");
  return <>
    <section className="surface-panel overflow-hidden">
      <div className="border-b border-slate-200 p-5 dark:border-white/10 md:p-7"><p className="text-xs font-bold text-slate-400">Proyectos <span className="mx-2">/</span> {project.layer} <span className="mx-2">/</span> <span className="text-slate-700 dark:text-slate-200">{project.title}</span></p><div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div className="max-w-4xl"><div className="flex flex-wrap gap-2"><StatusBadge>{project.status}</StatusBadge><span className="rounded-full border border-slate-200 px-3 py-1 text-xs font-bold text-slate-500 dark:border-white/10">{project.layer}</span></div><h1 className="mt-4 text-3xl font-black tracking-[-0.035em] text-slate-950 dark:text-white md:text-4xl">{project.title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-500 dark:text-slate-400">{project.objective}</p></div><Link href={`/escenarios/${project.id}`} className="primary-button flex">Abrir escenario<ArrowRight className="h-4 w-4" /></Link></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Meta icon={Users} label="Responsable" value={project.responsible} /><Meta icon={CalendarDays} label="Inicio" value={project.timeline} /><Meta icon={MapPin} label="Ubicación" value={project.neighborhood} /><Meta icon={BarChart3} label="Progreso general" value={project.reviewStatus ?? project.status} /><Meta icon={Clock3} label="Última actualización" value="Ficha vigente" /></div></div>
      <ProjectStageLine project={project} />
      <div className="urban-scrollbar flex overflow-x-auto border-t border-slate-200 px-3 dark:border-white/10">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`relative shrink-0 px-4 py-4 text-xs font-black uppercase tracking-[0.08em] ${tab === item ? "text-[#087bec]" : "text-slate-400 hover:text-slate-700 dark:hover:text-white"}`}>{item}{tab === item && <motion.span layoutId="project-tab" className="absolute inset-x-3 bottom-0 h-0.5 bg-[#1f89f6]" />}</button>)}</div>
    </section>
    <AnimatePresence mode="wait"><motion.div key={tab} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -4 }} transition={{ duration: 0.2 }} className="mt-5">{tab === "Resumen" ? <Summary project={project} /> : tab === "Historial" ? <DecisionHistory project={project} /> : <TabContent tab={tab} project={project} />}</motion.div></AnimatePresence>
  </>;
}

function ProjectStageLine({ project }: { project: UrbanProject }) {
  const stages = [{ name: "Propuesta", state: "done" }, { name: "Análisis", state: "done" }, { name: "Audiencia", state: project.linkedHearingId ? "current" : "pending" }, { name: "Escenarios", state: "pending" }, { name: "Decisión", state: "pending" }] as const;
  return <div className="p-5 md:p-7"><div className="relative grid min-w-0 grid-cols-5"><div className="absolute left-[10%] right-[10%] top-4 h-px bg-slate-200 dark:bg-white/10" />{stages.map((stage) => <div key={stage.name} className="relative z-10 text-center"><span className={`mx-auto grid h-8 w-8 place-items-center rounded-full border-4 border-white dark:border-[#0d1b2a] ${stage.state === "done" ? "bg-emerald-500 text-white" : stage.state === "current" ? "bg-[#1f89f6] text-white ring-4 ring-sky-400/15" : "bg-slate-200 text-slate-400 dark:bg-slate-700"}`}>{stage.state === "done" ? <Check className="h-4 w-4" /> : <Circle className="h-2.5 w-2.5 fill-current" />}</span><span className="mt-2 block text-[10px] font-bold text-slate-500 sm:text-xs">{stage.name}</span></div>)}</div></div>;
}

function Summary({ project }: { project: UrbanProject }) {
  return <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3"><InfoCard title="Contexto" icon={FileText} text={project.description} /><InfoCard title="Impacto territorial" icon={MapPin} items={project.impact} /><InfoCard title="Normativa relacionada" icon={Scale} text={project.codeRelation ?? "Pendiente de vinculación normativa"} /><InfoCard title="Participación" icon={Users} text={`${project.votes} apoyos y ${project.comments} intervenciones registradas.`} /><InfoCard title="Audiencias" icon={CalendarDays} text={project.linkedHearingId ? "Existe una audiencia pública vinculada a esta iniciativa." : "Sin audiencia vinculada."} /><InfoCard title="Análisis IA" icon={Sparkles} text={project.aiNormativeImpact ?? "Requiere análisis preliminar y validación técnica."} wide /></div>;
}

function DecisionHistory({ project }: { project: UrbanProject }) {
  const events = [{ date: "12 MAR", title: "Propuesta creada", detail: `Origen: ${project.origin}` }, { date: "18 MAR", title: "Análisis normativo ejecutado", detail: project.codeRelation ?? "Vinculación normativa pendiente" }, ...(project.linkedHearingId ? [{ date: "04 ABR", title: "Audiencia pública vinculada", detail: `${project.comments} intervenciones asociadas al proyecto` }] : []), { date: "08 ABR", title: "Síntesis técnica consolidada", detail: project.reviewStatus ?? "En revisión" }, { date: "16 ABR", title: "Escenario preparado para evaluación", detail: "Alternativas disponibles para revisión de gabinete" }];
  return <section className="surface-panel p-5 md:p-7"><p className="eyebrow">Trazabilidad</p><h2 className="mt-2 text-xl font-black text-slate-950 dark:text-white">Historial de decisiones</h2><div className="mt-7">{events.map((event, index) => <div key={event.title} className="grid grid-cols-[70px_24px_1fr] gap-3"><span className="pt-0.5 text-xs font-black text-slate-400">{event.date}</span><div className="relative flex justify-center"><span className="z-10 mt-1 h-2.5 w-2.5 rounded-full bg-[#1f89f6] ring-4 ring-sky-400/10" />{index < events.length - 1 && <span className="absolute bottom-0 top-3 w-px bg-slate-200 dark:bg-white/10" />}</div><div className="pb-7"><h3 className="font-black text-slate-950 dark:text-white">{event.title}</h3><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-400">{event.detail}</p></div></div>)}</div></section>;
}

function TabContent({ tab, project }: { tab: Tab; project: UrbanProject }) {
  const content: Record<Exclude<Tab, "Resumen" | "Historial">, { icon: typeof MapPin; title: string; body: string; items?: string[] }> = { Mapa: { icon: MapPin, title: "Contexto territorial", body: `${project.neighborhood} · Coordenadas ${project.position.join(", ")}` }, Normativa: { icon: Scale, title: "Normativa relacionada", body: project.codeRelation ?? "Pendiente de vinculación", items: [project.reviewStatus ?? project.status] }, Audiencias: { icon: CalendarDays, title: "Audiencias vinculadas", body: project.linkedHearingId ? "La audiencia forma parte de la trazabilidad del proyecto." : "No hay audiencias vinculadas." }, Participación: { icon: Users, title: "Participación ciudadana", body: `${project.votes} apoyos y ${project.comments} comentarios registrados.` }, Documentos: { icon: FileText, title: "Documentación", body: "Archivos técnicos asociados", items: project.attachedDocuments ?? [] }, "Análisis IA": { icon: Sparkles, title: "Análisis preliminar", body: project.aiNormativeImpact ?? "Requiere procesamiento y validación técnica.", items: project.risks }, Escenarios: { icon: BarChart3, title: "Escenarios de decisión", body: "Alternativas preparadas a partir de la evidencia disponible.", items: project.nextSteps } };
  const info = content[tab as keyof typeof content]; return <InfoCard title={info.title} icon={info.icon} text={info.body} items={info.items} wide />;
}

function Meta({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3 dark:bg-white/[0.03]"><Icon className="h-4 w-4 text-[#1f89f6]" /><p className="mt-3 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-slate-700 dark:text-slate-200">{value}</p></div>; }
function StatusBadge({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-700 dark:bg-amber-400/10 dark:text-amber-200">{children}</span>; }
function InfoCard({ title, icon: Icon, text, items, wide }: { title: string; icon: typeof FileText; text?: string; items?: string[]; wide?: boolean }) { return <article className={`surface-panel p-5 transition duration-200 hover:-translate-y-0.5 ${wide ? "lg:col-span-2 xl:col-span-2" : ""}`}><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-sky-50 text-[#087bec] dark:bg-sky-400/10"><Icon className="h-4 w-4" /></span><h2 className="font-black text-slate-950 dark:text-white">{title}</h2></div>{text && <p className="mt-4 text-sm leading-7 text-slate-500 dark:text-slate-400">{text}</p>}{items && <div className="mt-4 space-y-2">{items.map((item) => <div key={item} className="flex gap-2 text-sm leading-6 text-slate-500 dark:text-slate-400"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#1f89f6]" />{item}</div>)}</div>}</article>; }
